AdminSchool/AdminSchool/Models/SchoolTeacher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AdminSchool.Models
{
    public class SchoolTeacher
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Age should be a number between 1 to 18")]
        public int Age { get; set; }
        [Required(ErrorMessage ="Please insert again")]
        public int Salary { get; set; }
        [Required(ErrorMessage ="Please insert your first name again")]
        [StringLength(50)]
        public string FirstName { get; set; }
        [Required(ErrorMessage ="Please insert your last name again")]
        [StringLength(50)]
        public string LastName { get; set; }
        [Required(ErrorMessage ="Please insert a valid position")]
        [StringLength(50)]
        public string Position { get; set; }
    }
}

AdminSchool/AdminSchool/Controllers/SchoolTeachersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdminSchool.DataAccesslayer;
using AdminSchool.Models;
using PagedList;
using PagedList.Mvc;

namespace AdminSchool.Controllers
{
    public class SchoolTeachersController : Controller
    {
        private SutdentRegisterContext db = new SutdentRegisterContext();

        // GET: SchoolTeachers
        public ActionResult Index(int? page, string searchBy, string search)
        {
            //if (string.IsNullOrEmpty(search))
            //{
            //    return (db.Schoolteachers.ToList().ToPagedList(page ?? 1, 2));
            //}

            if (searchBy == "FirstName")
            {
                return View(db.Schoolteachers.Where(x => x.FirstName == search ||  search == null).ToList().ToPagedList(page ?? 1, 2));
            }
            else if(searchBy == "LastName")
            {
                return View(db.Schoolteachers.Where(x => x.LastName == search || search == null).ToList().ToPagedList(page ?? 1, 2));

            }
            else if (searchBy == "Age")
            {
                return View(db.Schoolteachers.Where(x => x.Age.ToString() == search || search == null).ToList().ToPagedList(page ?? 1, 2));

            }
            else if (searchBy == "Slary")
            {
                return View(db.Schoolteachers.Where(x => x.Salary.ToString() == search || search == null).ToList().ToPagedList(page ?? 1, 2));

            }
            else if(searchBy == "Position")
            {
                return View(db.Schoolteachers.Where(x => x.Position == search || search == null).ToList().ToPagedList(page ?? 1, 2));

            }
            else
            {
                return View(db.Schoolteachers.Where(x => x.FirstName.StartsWith(search) || search == null).ToList().ToPagedList(page ?? 1, 2));

            }
            //return (db.Schoolteachers.ToList().ToPagedList( page ?? 1, 2));


        }

        // GET: SchoolTeachers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SchoolTeacher schoolTeacher = db.Schoolteachers.Find(id);
            if (schoolTeacher == null)
            {
                return HttpNotFound();
            }
            return View(schoolTeacher);
        }

        // GET: SchoolTeachers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SchoolTeachers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Age,Salary,FirstName,LastName,Position")] SchoolTeacher schoolTeacher)
        {
            if (ModelState.IsValid)
            {
                db.Schoolteachers.Add(schoolTeacher);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(schoolTeacher);
        }

        // GET: SchoolTeachers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SchoolTeacher schoolTeacher = db.Schoolteachers.Find(id);
            if (schoolTeacher == null)
            {
                return HttpNotFound();
            }
            return View(schoolTeacher);
        }

        // POST: SchoolTeachers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Age,Salary,FirstName,LastName,Position")] SchoolTeacher schoolTeacher)
        {
            if (ModelState.IsValid)
            {
                db.Entry(schoolTeacher).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(schoolTeacher);
        }

        // GET: SchoolTeachers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SchoolTeacher schoolTeacher = db.Schoolteachers.Find(id);
            if (schoolTeacher == null)
            {
                return HttpNotFound();
            }
            return View(schoolTeacher);
        }

        // POST: SchoolTeachers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SchoolTeacher schoolTeacher = db.Schoolteachers.Find(id);
            db.Schoolteachers.Remove(schoolTeacher);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdminSchool/AdminSchool/Views/SchoolTeachers/Create.cshtml
@model AdminSchool.Models.SchoolTeacher

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SchoolTeacher</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control", @min="1", @placeholder="Age"} })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control", @min="13000", @max="50000", @placeholder="Salary"} })
                @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", @placeHolder="First Name" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", @placeholder="last Name" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control", @placeholder="Position"} })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <button class="btn btn-default">@Html.ActionLink("Back to List", "Index")</button>  
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AdminSchool/AdminSchool/Views/SchoolTeachers/Delete.cshtml
@model AdminSchool.Models.SchoolTeacher

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SchoolTeacher</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button class="btn btn-default">@Html.ActionLink("Back to List", "Index")</button>
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }
</div>

AdminSchool/AdminSchool/Views/SchoolTeachers/Details.cshtml
@model AdminSchool.Models.SchoolTeacher

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SchoolTeacher</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>

    </dl>
</div>
<p>
    <button class="btn btn-default">@Html.ActionLink("Back to List", "Index")</button>
    <button class="btn btn-default">@Html.ActionLink("Edit", "Edit", new { id = Model.Id })</button>
</p>

AdminSchool/AdminSchool/Views/SchoolTeachers/Edit.cshtml
@model AdminSchool.Models.SchoolTeacher

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SchoolTeacher</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <button class="btn btn-default">@Html.ActionLink("Back to List", "Index")</button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AdminSchool/AdminSchool/Views/SchoolTeachers/Index.cshtml
@model IPagedList<SchoolTeacher>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div class="row">
    <p>
        <button class="btn btn-default">@Html.ActionLink("Create New", "Create")</button>
    </p>
    <div class="jumbotron">
        <p>
            @using (Html.BeginForm("Index", "SchoolTeachers", FormMethod.Get))
            {
                <b>Search by:</b>
                @Html.RadioButton("SearchBy", "Age", true) <text> Age</text>
                @Html.RadioButton("SearchBy", "Salary") <text> Salary</text>
                @Html.RadioButton("SearchBy", "FirstName") <text> FirstName </text>
                @Html.RadioButton("SearchBy", "LastName") <text> LastName</text>
                @Html.RadioButton("SearchBy", "Position") <text> Position</text><br />
                @Html.TextBox("search", null, new { @class = "form-control", placeholder = "Search for..." })<input type="submit" value="Search" class="btn btn-info"/>
            }
        </p>
    </div>
</div>

<table class="table table-hover table-striped table-responsive">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Salary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Position)
        </th>
        <th></th>
    </tr>
    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="6">We are sorry No rows match search critiria. Try again.</td>
        </tr>
    }
    else
    { 
    foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Age)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salary)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Position)
        </td>
        <td>
            <button class="btn btn-default">@Html.ActionLink("Edit", "Edit", new { id = item.Id })</button>
            <button class="btn btn-default">@Html.ActionLink("Details", "Details", new { id = item.Id })</button>
            <button class="btn btn-default">@Html.ActionLink("Delete", "Delete", new { id = item.Id })</button> 
        </td>
    </tr>
}
    }
</table>
<div class="row">
    @Html.PagedListPager(Model, Page => Url.Action("Index", new { Page, searchBy = Request.QueryString["searchBy"], search = Request.QueryString["search"]}),
    new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true, DisplayItemSliceAndTotal = true})
</div>